# Generated by Django 4.2.27 on 2026-01-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_status_a5ad2e_idx',
            old_name='payout_status_idx',
        ),
    ]
